config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  scope format: false, constraints: {path: /[a-zA-Z0-9_\/]*/} do
    get    '/(*path)/add',  to: 'pages#new',    as: :new_page
    get    '/(*path)/edit', to: 'pages#edit',   as: :edit_page
    get    '/(*path)',      to: 'pages#show',   as: :page
    post   '/(*path)/add',  to: 'pages#create'
    patch  '/(*path)/edit', to: 'pages#update'
    put    '/(*path)/edit', to: 'pages#update'
    delete '/(*path)',      to: 'pages#destroy'
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend ActsAsTree::TreeWalker
  acts_as_tree order: 'slug'

  before_validation :generate_slug
  before_destroy :check_children, prepend: true

  validates_presence_of :title
  validates_presence_of :text
  validates :slug,
    format: {
      with: /\A[a-zA-Z0-9_]*\z/,
      message: 'can contain only english letters, numbers and underscores'
    },
    exclusion: {
      in: %w(edit add),
      message: 'can’t be “%{value}”: it’s a reserved word'
    },
    uniqueness: {
      scope: :parent_id
    }
  validates_uniqueness_of :parent_id,
    if: :root?,
    message: 'can be omitted only on root page'
  validates_presence_of :parent,
    unless: :root?


  def self.find_root
    find_by(parent_id: nil)
  end

  def self.find_by_path(path)
    slugs = path.to_s.split('/').unshift('')

    sql = 'SELECT pl.* FROM pages pl '

    slugs[0..-2].each_with_index do |slug, i|
      sql << "JOIN pages p#{i} ON "
      if i == 0
        sql << "p#{i}.parent_id IS NULL "
      else
        sql << "p#{i}.slug = '#{slug}' AND p#{i}.parent_id = p#{i - 1}.id "
      end
    end

    if slugs.length < 2
      sql << 'WHERE pl.parent_id IS NULL;'
    else
      sql << "WHERE pl.slug = '#{slugs.last}' AND pl.parent_id = p#{slugs.length - 2}.id;"
    end

    self.find_by_sql(sql).first
  end


  def root?
    !(parent || parent_id)
  end

  def path
    if parent.present? && (parent_path = parent.path).present?
      "#{parent_path}/#{slug}"
    else
      slug.to_s
    end
  end

  def text_html
    KindamarkupHtml.to_html(text)
  end

  def title_with_path
    if path.present?
      "#{title} (#{path})"
    else
      title
    end
  end

  def to_param
    path
  end

  def check_children
    unless leaf?
      errors[:base] << 'Page cannot be destroyed because it has children'
      false
    end
  end

  def generate_slug
    if slug.blank? && !root? && title.present?
      I18n.with_locale(:ru) do
        self.slug = title.to_s.parameterize('_')
      end

      if (taken_slugs = Page.where('parent_id = ? AND slug LIKE ?', parent_id, "#{slug}%").pluck(:slug)).present?
        i = 1
        possible_slug = slug

        while taken_slugs.include? possible_slug do
          i += 1
          possible_slug = "#{slug}_#{i}"
        end

        self.slug = possible_slug
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :destroy]

  def index
    @page = Page.find_root

    if @page.present?
      render 'show'
    else
      @page = Page.new(
        slug: '',
        title: 'Root page',
        text: "Welcome to kindawiki!\nIt looks like you db is empty."
      )
      render 'new'
    end

  end

  def show
  end

  def new
    parent = Page.find_by_path(params[:path])

    if parent.present?
      @page = Page.new(parent: parent)
    else
      if Page.exists?
        redirect_to new_page_path('')
      else
        redirect_to root_path
      end
    end
  end

  def edit
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to @page, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def update
    @page = Page.find_by_path(params[:path])

    if @page.present?
      if @page.update(page_params)
        redirect_to @page, notice: 'Page was successfully updated.'
      else
        render :edit
      end
    else
      flash[:notice] = 'Requested page doesn’t exist! But you can create one'
      @page = Page.new(page_params)
      render :new
    end
  end

  def destroy
    target = if @page.parent.present?
      page_path @page.parent
    else
      root_path
    end

    if @page.destroy
      redirect_to target, notice: 'Page was successfully destroyed.'
    else
      redirect_to edit_page_path(@page), notice: @page.errors.messages[:base].join(', ')
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find_by_path(params[:path])

    raise ActionController::RoutingError.new('Not Found') unless @page.present?
  end

  # Only allow a trusted parameter "white list" through.
  def page_params
    params.require(:page).permit(:title, :text, :slug, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    if @page.present? && @page.title.present?
      "#{@page.title} — Kindawiki"
    else
      'Kindawiki'
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', :'http-equiv' => 'Content-Type'}
    %meta{:content => 'IE=edge', :'http-equiv' => 'X-UA-Compatible'}
    %meta{:content => 'width=device-width, initial-scale=1', :name => 'viewport'}

    %title= page_title
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %header
      .navbar.navbar-default
        .container
          .navbar-header
            %a.navbar-brand{href: '/'} Kindawiki
    - if notice.present?
      %section
        .container
          .row
            .col-xs-12.alert.alert-info.alert-dismissible{role: 'alert'}
              %button.close{:'aria-label' => 'Close', :'data-dismiss' => 'alert', :type => 'button'}
                %span{:'aria-hidden' => 'true'} ×
              != notice

    %section.main-section
      .container
        .row.white-block
          .col-xs-12
            = yield

app/views/pages/_form.html.haml
= form_for @page, url: form_url, html: { class: 'form-horizontal' } do |f|
  - if @page.errors.any?
    .alert.alert-warning.alert-dismissible{role: 'alert'}
      %button.close{:'aria-label' => 'Close', :'data-dismiss' => 'alert', :type => 'button'}
        %span{:'aria-hidden' => 'true'} ×
      #{pluralize(@page.errors.count, 'error')} prohibited this page from being saved:
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    - unless @page.root?
      .form-group
        = f.label :parent_id, class: 'col-sm-2 control-label' do
          Parent
        .col-sm-10
          :ruby
            family_tree = []
            nbsp = "\u00a0"
            statement = @page.id ? ['id != ?', @page.id] : nil
            Page.walk_tree(where: statement){ |p, i| family_tree << ["#{nbsp * 2 * i}#{p.title_with_path}", p.id] }
          = f.select(:parent_id,
            options_for_select(family_tree, selected: @page.parent_id, disabled: @page.id),
            {}, class: 'form-control')

      .form-group{title: 'You can use english letters, numbers and underscores'}
        = f.label :slug, class: 'col-sm-2 control-label' do
          Page slug
        .col-sm-10
          = f.text_field :slug, class: 'form-control', pattern: '[a-zA-Z0-9_]*'

    .form-group
      = f.label :title, class: 'col-sm-2 control-label' do
        Page title
      .col-sm-10
        = f.text_field :title, class: 'form-control', required: true

    .form-group
      = f.label :text, class: 'col-sm-2 control-label' do
        Page text
      .col-sm-10
        = f.text_area :text, class: 'form-control', rows: 10

  %fieldset
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit 'Save', class: 'btn btn-primary'
        - if @page.persisted?
          = link_to 'Back to page', page_url(@page), class: 'btn btn-default'
          - unless @page.root?
            - if @page.children.exists?
              %span{title: 'Page has children and cannot be deleted'}
                %a.btn.btn-danger.disabled Delete
            - else
              = link_to 'Delete', page_url(@page), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'

app/views/pages/_node.html.haml
%li
  = link_to node.title, node
  = link_to edit_page_path(node), title: 'Edit' do
    %span.glyphicon.glyphicon-pencil
  - if node.children.exists?
    %ul
      = render partial: 'node', collection: node.children

app/views/pages/edit.html.haml
%h1 Editing page “#{@page.title}”

= render 'form', form_url: edit_page_path(params[:path])

app/views/pages/new.html.haml
%h1 New page

= render 'form', form_url: new_page_path(params[:path])

app/views/pages/show.html.haml
%ol.breadcrumb
  - @page.ancestors.reverse.each do |crumb|
    %li
      = link_to crumb.title, crumb
  %li.active
    = @page.title

%h1!= @page.title

.text
  != @page.text_html

- if @page.children.exists?
  .tree
    %h3 Subpages:
    %ul
      = render partial: 'node', collection: @page.children

.page-buttons
  = link_to 'Edit page', edit_page_path(@page), class: 'btn btn-default'
  = link_to 'Add subpage', new_page_path(@page), class: 'btn btn-default'